### ISSUE TITLE
provider: Privileged Names

### ISSUE THREAD

**Issue by Valodim** [katzenpost/server#27]
For various purposes, it would be nice to have a way of having "privileged"
mix-names on providers. This can be done by declaring some namespace as
privileged, and only allowing its use if listed directly in the Katzenpost
provider's configuration, "pinning" it to a fixed the link-key. Privileged names
do not have any privileges over regular names, other than the name itself (think
privileged ports).

An explicit namespace for privileged services avoids the problems of email that
occur when special meaning is assigned to names like "postmaster", "admin", or
"root" on the application layer.

As a concrete proposal, names starting with a + character (e.g.
"+service@provider.example") could be restricted from general use.

**Comment by Yawning** [comment]
This feels like a policy decision rather than something that should be done programmatically to me.

Currently apart from a minimum and maximum length, there are no restrictions on user names (`+service`), and it is up to the operator of each provider to assign useful meanings to the user identifier.

If providers on a particular mixnet decide (for example) that they want to use binary user identifiers, the server should support this.  If the LEAP providers want to reserve a portion of the namespace, then they are free to do so as well, but that shouldn't apply to other networks.

**Comment by Yawning** [comment]
I'm closing this as a WONTFIX.  The draft auto responder design publishes endpoints to the entire network, and while things should be consistent, this is entirely a policy decision.

**Comment by Valodim** [comment]
:+1:
