### ISSUE TITLE
Queue Management Algorithm

### ISSUE THREAD

**Issue by mavroudisv** [katzenpost/server#35]
I'd like to share some thoughts/reservations for the current AQM approach. 

The algorithm here seems straightforward (?) and correct:
https://github.com/katzenpost/core/blob/cfafa3cd6c3b2650fd221d20e56c40a775824bbd/queue/priority_queue.go#L101

My concerns are on how it's used here:
https://github.com/katzenpost/server/blob/894995e2d0bddc752efac7f12005f7a291a866bf/schedule.go#L84-L92

It seems as if the incoming packet is not a candidate for dropping, and we just pick a packet at random from those already in the queue.

If that's correct, a DoS or DDoS attack is fairly easy to launch. The adversary needs to keep sending packets until she replaces all the "benign" packets in the queue.

I haven't worked out yet the expected number of "adversarial" packets that it'd take for an adversary to fully replace all "benign" packets, but I believe it'll be a multiple of the queue size (maybe sth close to log(queue_size)*queue_size).

Looking forward to your thoughts and please let me know if I missed something. :)

Cheers!
Vasilis

**Comment by Yawning** [comment]
Hello,

Thanks for the feedback, and I hope the source wasn't too painful to read.

Yes, that seems right.  My first stab at an "easy" fix would be to enqueue the packet then drop for now, unless there's more that you think I could do here.  In the longer term, I have grand plans of using a more sophisticated disk backed priority queue (katzenpost/core#11) that should hopefully make this sort of attack a lot harder, but alas that's firmly in the realm of "future improvements" since there's more urgent things needed for pre-alpha.

**Comment by david415** [comment]
Sure we can fix/modify this... although I should point out that we aren't completely sure about preventing DOS attacks:

In general this DOS attack still works even if we enqueue the packet first before selecting a random packet to drop. Just like other packet switching networks, we can use a particular fair AQM for ingress packets before they even get to the our mix strategy queue... such as "Resilient Stochastic Fair Blue" AQM or other fair AQMs designed to mitigate DOS attacks. Obviously it only makes sense to use fair AQMs on Providers since only Providers can observe client IP addresses.

**Comment by Yawning** [comment]
While there is a bunch of ingress side controls that can potentially mitigate this problem (#33 also being a "easy" fix), it is probably hard to impossible to prevent the mix queue from getting full, especially if the adversary has the capability of utilizing multiple accounts.

As far as I can tell the best that can be done is to try to make the service degrade gracefully under load as much as possible, and provide providers the tooling required to identify abusive behavior in a privacy preserving way.
