### ISSUE TITLE
mix queue should communicate with ingress AQM?

### ISSUE THREAD

**Issue by david415** [katzenpost/server#46]
I'm here at KU Leuven with Tariq and Claudia. We are discussing the ingress AQM drop strategy. If we understand things correctly the ingress AQM drops packets if they dwell longer than unwrapSlack:

```
		// Drop the packet if it has been sitting in the queue waiting to
		// be unwrapped for way too long.
		if unwrapDelay := now - pkt.RecvAt; unwrapDelay > unwrapSlack {
			w.log.Debugf("Dropping packet: %v (Spent %v waiting for Unwrap())", pkt.ID, unwrapDelay)
			pkt.Dispose()
			continue
```

Isn't this essentially CoDel?

Claudia is suggesting that the majority of packet drops should ideally happen in the ingress queue... but those packet drops should be random instead of based on the criteria of dwell time. An active attacker could game the system and force certain packets to be dropped without affecting others. One possibility is that the mix queue could communicate congestion to the ingress queue... such that the probability of dropping packets in the ingress queue is greater than the mix queue.

Tariq and Claudia are available for an e-mail discussion about this.

**Comment by Yawning** [comment]
I don't think this matters, and would be a lot of work because there's no easy way to get at the internal go channel buffer (if at all).  This check is there to prevent unbound growth of the crypto worker work queue (CPU overload).  In order for this to happen, one of two things need to be true:

 * The node is pathologically under-provisioned (eg: No AES-NI support, not enough cores, etc).
 * The node is on something substantially larger than a 1Gbit link (and the replay cache fast path falls over).

I don't think it's physically possible for the crypto worker to actually fall behind currently for 1Gbit links on systems with hardware accelerated AES because the network interface will saturate well before CPU resources becomes a problem.
