### ISSUE TITLE
crypto_workers sets delay to 0

### ISSUE THREAD

**Issue by david415** [katzenpost/server#47]
Here we are setting the mix queue delay to zero if the dwell time is equal or greater than the hop delay:

crypto_worker.go line 206 or so:
```
			dwellTime := now - pkt.RecvAt
			if pkt.Delay > dwellTime {
				pkt.Delay -= dwellTime
			} else {
				// Eeep, the dwell time has exceeded the user requested delay.
				//
				// TODO: Either can drop or dispatch the packet immediately,
				// I'm not sure which is better behavior.
				pkt.Delay = 0
			}
```

Under certain conditions this could turn our mix strategy queue into a FIFO which would be bad. I think it would be better to drop these packets rather then try to send them out immediately... although we would ideally drop them before they even get to this stage of the pipeline.

**Comment by Yawning** [comment]
This also is unlikely to happen, though it can if the user selects an extremely short delay (I suspect it will only happen currently if the delay is exactly 0, because dwell time under normal operation is < 1 ms).

I am of the opinion that either a minimum delay should be enforced (because a delay of 0 is impossible) or the check and adjustment should be removed entirely in this case (because fudging a ms granular quantity for a sub-ms wait is silly and somewhat pointless).

**Comment by Yawning** [comment]
This is "fixed" now.  I still think adjusting the delay should be a best effort thing, but now the edge cases are either discarded or have delay forced.
